### ISSUE TITLE
Inverse Kinematics

### ISSUE THREAD

**Issue by 915-Narita-Andrei** [Yeok-c/Stewart_Py#5]
Can you explain why you stated in the Jupiter Notebook at inverse Kinematics with Rotational Servos that:
h = H - B
d = P - H
l = P - B
and after that why the square of the lengths of this is that system? the T is meant to be the transpose matrix?

**Comment by Yeok-c** [comment]
> Can you explain why you stated in the Jupiter Notebook at inverse Kinematics with Rotational Servos that:
> h = H - B
> d = P - H
> l = P - B

From the first diagram in the 'Inverse Kinematics with Rotational Servos', you can see how h_k, d_k, l_k are the vectors representing each servo horn, rod, and leg. To get this vector, you only need to subtract the end of the vector from the origin of the vector. 
So eg. the vector representing the kth leg, is just position of the kth platform anchor - position of kth base anchor ie. l_k = P_k - B_k

Since the arithmetic operation for all 6 legs are the same, you can concatenate l_1, l_2, l_3... l_6 into a R(6x1) vector _l_ 


> and after that why the square of the lengths of this is that system? the T is meant to be the transpose matrix?

It's just a way to solve the equations. Because the vectors like (H-B) is a R(6x1) vector, when you square it you need to do (H-B)^T * (H-B).

**Comment by 915-Narita-Andrei** [comment]
> Thanks a lot for helping me. It was in front of my eyes but I couldn't see it
